x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    container_name: postgres

    image: postgres:15-alpine

    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: template
      POSTGRES_USER: template

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template"]
      interval: 2s
      timeout: 1s
      retries: 5

  networks:
  - database-access

  api:
    <<: *logging

    build:
      context: ./api
      dockerfile: Dockerfile

    environment:
      TEMPLATE_API_ENVIRONMENT: "dev"
      TEMPLATE_API_DB_HOST: "postgres"
      TEMPLATE_API_HOST: "0.0.0.0"

    ports:
    - "127.0.0.1:8001:8001"

    volumes:
    - ./api:/api

    networks:
    - database-access

networks:
  database-access:
    name: database-access
    external: true
