version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    container_name: postgres

    image: postgres:15-alpine

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: template
      POSTGRES_USER: template

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template"]
      interval: 2s
      timeout: 1s
      retries: 5

  adminer:
    <<: *logging

    container_name: adminer

    image: adminer:latest

    ports:
      - "8080:8080"
