name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix: { dir: ["api"] }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: "${{ matrix.dir }}/pyproject.toml"

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: ${{ matrix.dir }}
      run: pdm sync

    - name: Run lints
      working-directory: ${{ matrix.dir }}
      run: pdm lint

    - name: Run tests
      working-directory: ${{ matrix.dir }}
      run: pdm test

  site-ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix: { dir: ["site"] }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: yarn install

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: yarn lint
